on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sed '${{ github.event.inputs.logLevel }}' 1.txt
        sed '${{ github.event.inputs.tags }}' 1.txt
