on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          date > generated2.txt
          date > generated5.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./generated5.txt
          git commit -m "generated"
          git push
