on: 
  workflow_dispatch:
    inputs:
      cookie:
        description: '输入Cookie'     
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
    - env:
        COOKIE: ${{ github.event.inputs.cookie }}
      run: |
        python py.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./5.txt
        git commit -m "test"
        git push
